### ISSUE TITLE
Error installing on buster systems

### ISSUE THREAD

**Issue by fredclausen** [sdr-enthusiasts/docker-install#1]
```
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://archive.raspberrypi.org/debian buster InRelease' changed its 'Suite' value from 'testing' to 'oldstable'
```

**Comment by fredclausen** [comment]
```sudo apt-get update --allow-releaseinfo-change```

Appears to bypass the issue. I'm not sure this is a real problem, or if it is, one worth fixing.

**Comment by kx1t** [comment]
Seems worthy of a note in the README instead of a script fix:

This is an action for which `apt` feels that it needs manual user acknowledgement, and we should respect that and not overrule it in the script.

**Comment by kx1t** [comment]
I pushed the documentation change directly to the repo (no PR needed).
