### ISSUE TITLE
docker-swarm support?

### ISSUE THREAD

**Issue by dlasher** [sdr-enthusiasts/docker-install#17]
Even with a beefy ARM based machine (playing with the oDroid N2+ now) if you live in an area of high 1090 traffic, you can overload a single docker host. To that end, I've been playing around with docker swarm, thinking about breaking the decode/feeders/etc across several pi, but all the compose/run/etc commands (and shared data directories) assume a single host.

Any thoughts/plans/etc to support swarm  (aka docker services)?

thanks.

**Comment by daleghent** [comment]
The cost of multiple RPIs will get you a single nice Celeron N5105 or i3 mini PC that can do it all.

**Comment by dlasher** [comment]
> The cost of multiple RPIs will get you a single nice Celeron N5105 or i3 mini PC that can do it all.

_I guess I left that open ended when I asked "any thoughts"_

**Any productive thoughts specific to docker swarm support?**

**Comment by kx1t** [comment]
Sorry for the slow answering -- going through reviewing a bunch of open issues that I **thought** had already been address, but for some reason, we didn't 🤷‍♂️

In any case, right now we have no plans to automatically setup Docker Swarms. This doesn't mean that it's wrong, or not interesting, but we're already a bit overwhelmed with projects and tbh you're the first one asking for it. So unless you want to do the work in such a way that it becomes an add-on feature for this repo (and we'll be happy to review any PRs for that!), I'm closing this issue for now as something we won't do. Feel free to reopen if you want to discuss further.

In any case - thanks for bringing it up and sorry for the awful delay in answering.
