### ISSUE TITLE
doing stuff that's already done

### ISSUE THREAD

**Issue by dirkhh** [sdr-enthusiasts/docker-install#9]
is there a reason why you aren't checking whether the user is already in `sudoers`?
Similary, you are pre-pending `/usr/bin` to the `$PATH` - that will get you duplicate entries if it's already there.

Neither of these is a big deal - but it seems like such a carefully written script, so I wondered...

**Comment by kx1t** [comment]
Both of those are "good to haves". The original idea was that the script is run right after an initial install of the OS, but it can obviously be used when adding Docker to an existing installed OS as well.

Would you want to propose some changes and do a PR? Happy to accept them :)
Thanks!

**Comment by kx1t** [comment]
fixed in https://github.com/sdr-enthusiasts/docker-install/commit/48e41b9f2a5f16d907f3811e71c5b1caee7bfc05
